---
permalink: protect-scsql/concept_how_long_to_retain_transaction_log_backups_on_the_source_storage_system.html 
sidebar: sidebar 
keywords: retain transaction log backups 
summary: Das SnapCenter Plug-in für Microsoft SQL Server benötigt Transaktions-Log-Backups, um minutengenaue Restore-Vorgänge durchzuführen, bei denen Ihre Datenbank zwischen zwei vollständigen Backups wiederhergestellt wird. 
---
= Wie lange werden Transaktions-Log-Backups auf dem Quell-Storage-System aufbewahrt
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das SnapCenter Plug-in für Microsoft SQL Server benötigt Transaktions-Log-Backups, um minutengenaue Restore-Vorgänge durchzuführen, bei denen Ihre Datenbank zwischen zwei vollständigen Backups wiederhergestellt wird.

Wenn zum Beispiel Plug-in für SQL Server um 8:00 Uhr ein vollständiges Backup und um 5:00 Uhr ein weiteres komplettes Backup erstellt hat, könnte es die letzte Sicherung des Transaktionsprotokolls verwenden, um die Datenbank zwischen 8:00 Uhr und 5:00 Uhr wiederherzustellen. Wenn Transaktionsprotokolle nicht verfügbar sind, das Plug-in für SQL Server kann nur Point-in-Time-Wiederherstellungsvorgänge durchführen, die eine Datenbank so lange wiederherstellen, wie das Plug-in für SQL Server ein vollständiges Backup abgeschlossen hat.

In der Regel erfordern Sie minutengenaue Restore-Vorgänge nur für einen oder zwei Tage. SnapCenter speichert standardmäßig mindestens zwei Tage.
