---
permalink: upgrade/task_upgrade_snapcenter.html 
sidebar: sidebar 
keywords: upgrade, upgrade snapcenter server, windows 
summary: Sie können die ausführbare Datei für das SnapCenter-Server-Installationsprogramm verwenden, um den SnapCenter-Server zu aktualisieren. 
---
= Aktualisieren Sie den SnapCenter-Server auf dem Windows-Host
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie sollten den SnapCenter -Server aktualisieren, um auf die neuesten Funktionen und Verbesserungen der neuesten Version zugreifen zu können.

.Bevor Sie beginnen
* Der SnapCenter-Server-Host muss mit Windows-Updates auf dem neuesten Stand sein, ohne dass das System neu gestartet werden muss.
* Stellen Sie sicher, dass keine anderen Vorgänge ausgeführt werden, bevor Sie mit dem Upgrade beginnen.
* Sichern Sie die SnapCenter -Repository-Datenbank (MySQL), nachdem Sie sichergestellt haben, dass keine Jobs ausgeführt werden.  Dies wird vor dem Upgrade von SnapCenter Server und dem Exchange-Plug-In empfohlen.
+
Weitere Informationen finden Sie unter link:../admin/concept_manage_the_snapcenter_server_repository.html#back-up-the-snapcenter-repository["Sichern des SnapCenter Repositorys"^].

* Sichern Sie alle geänderten SnapCenter -Konfigurationsdateien entweder auf dem SnapCenter Server-Host oder dem Plug-In-Host.


Beispiele für SnapCenter-Konfigurationsdateien: SnapDriveService.exe.config, SMCoreServiceHost.exe.config usw.

* Wenn Sie mehrere Versionen des benutzerdefinierten Plug-Ins in SnapCenter 5.0 installiert haben, sollten Sie vor dem Upgrade auf 6.0 oder höher die Powershell-Cmdlets ausführen, um alle früheren Versionen des benutzerdefinierten Plug-Ins (mit Ausnahme der neuesten) aus dem SnapCenter Repository (NSM-Datenbank) zu entfernen.
+
** Laufen `Open-SmConnection` und melden Sie sich mit den Anmeldeinformationen der SnapCenterAdmin-Rolle an
** Laufen `Remove-SmPluginPackage -PluginName M<plug-in name> -PluginVersion <version number>`
+
Weitere Informationen finden Sie unter  https://kb.netapp.com/data-mgmt/SnapCenter/SC_KBs/SnapCenter_6.0_upgrade_fails_in_nsm_repository_upgrade_SQL_script_8["Das Upgrade auf SnapCenter 6.0 oder höher schlägt fehl"] .





.Über diese Aufgabe
* Während des Upgrades führt SnapCenter ein SQL-Skript aus, um die Exchange-Daten in der NSM-Datenbank zu aktualisieren und den DAG- und Host-Kurznamen in FQDN umzuwandeln.  Dies gilt nur, wenn Sie SnapCenter Server mit dem Exchange-Plug-In verwenden.
* Wenn Sie den Serverhost manuell in den Wartungsmodus versetzt haben, wählen Sie nach dem Upgrade *Hosts* > *Zeitplan aktivieren*, um den Serverhost aus dem Wartungsmodus zu holen.
* Für das SnapCenter Plug-in für Microsoft SQL Server, das SnapCenter Plug-in für Microsoft Exchange Server und das SnapCenter Plug-in für Microsoft Windows wird empfohlen, für DIE Ausführung VON SCRIPTS_PATH sowohl den Server als auch die Plug-in-Hosts auf die Version 4.7 zu aktualisieren.
+
Für die bestehenden Backup- und Verifizierungspläne mit aktivierten in der Richtlinie aktivierten Prescripts und Postscripts funktionieren die Backup-Vorgänge nach dem Upgrade weiterhin.

+
Auf der Seite *Job Details* empfiehlt eine Warnmeldung, dass der Kunde die Skripte in DEN SCRIPTS_PATH kopieren und die Richtlinie bearbeiten sollte, um einen Pfad bereitzustellen, der sich auf den SCRIPTS_PATH bezogen. Für den Clone Lifecycle Job wird die Warnmeldung auf der Unterauftragsebene angezeigt.



.Schritte
. Laden Sie das SnapCenter Server-Installationspaket von der NetApp Support Website herunter.
+
https://mysupport.netapp.com/site/products/all/details/snapcenter/downloads-tab[]

. Erstellen Sie eine Kopie von Web.config unter C:\Programme\NetApp\SnapCenter WebApp.
. Exportieren Sie die Host-Zeitpläne des SnapCenter -Plug-Ins aus dem Windows-Taskplaner, um sie wiederherzustellen, falls das Upgrade fehlschlägt.
+
`md d:\\SCBackup``schtasks /query /xml /TN taskname >> "D:\SCBackup\taskname.xml"`

. Erstellen Sie den SnapCenter MySQL Datenbank-Dump, wenn das Repository-Backup nicht konfiguriert ist.
+
`md d:\\SCBackup``mysqldump --all-databases --single-transaction --add-drop-database --triggers --routines --events -u root -p > D:\SCBackup\SCRepoBackup.dmp`

+
Geben Sie bei der entsprechenden Aufforderung das Passwort ein.

. Doppelklicken Sie auf die heruntergeladene EXE-Datei, um das SnapCenter Server-Upgrade zu starten.
+
Nachdem Sie das Upgrade gestartet haben, führt SnapCenter Vorprüfungen durch.  Wenn das System die Mindestanforderungen nicht erfüllt, zeigt SnapCenter Fehler- oder Warnmeldungen an.  Beheben Sie alle Fehler, bevor Sie fortfahren.  Sie können Warnungen ignorieren und fortfahren.

+

NOTE: SnapCenter verwendet weiterhin das vorhandene Datenbankkennwort für das MySQL-Server-Repository, das bei der Installation der früheren Version von SnapCenter Server angegeben wurde.

. Wählen Sie *Upgrade*.
+
Wenn Sie zu irgendeinem Zeitpunkt *Abbrechen* auswählen, stoppt SnapCenter das Upgrade.  Der SnapCenter -Server wird nicht in seinen vorherigen Zustand zurückgesetzt.

+
*Best Practice:* Melden Sie sich ab und erneut an oder öffnen Sie einen neuen Browser, um auf die SnapCenter Benutzeroberfläche zuzugreifen.



.Nachdem Sie fertig sind
* Wenn das Plug-in mit einem Sudo-Benutzer installiert wird, sollten Sie die unter _C:\ProgramData\NetApp\SnapCenter\Package Repository\sc_unix_Plugins_Checksumme.txt_ verfügbaren sha224-Schlüssel kopieren, um die _/etc/sudoers_-Datei zu aktualisieren.
* Sie sollten eine neue Ermittlung der Ressourcen auf dem Server-Host durchführen.
+
Wenn SnapCenter den Server-Hoststatus als „gestoppt“ anzeigt, warten Sie einige Zeit und führen Sie eine neue Erkennung durch.  Sie können den Wert des Parameters *HostRefreshInterval* (Standardwert ist 3600 Sekunden) auch auf einen beliebigen Wert über 10 Minuten ändern.

* Wenn das Upgrade fehlschlägt, bereinigen Sie die fehlgeschlagene Installation, installieren Sie die vorherige SnapCenter -Version neu und stellen Sie den vorherigen Zustand der NSM-Datenbank wieder her.
* Nach dem Upgrade des Server-Hosts müssen Sie auch die Plug-ins aktualisieren, bevor Sie ein Speichersystem hinzufügen.

